export default {
  SET_COLLECTIONS: 'SET_COLLECTIONS',
  SET_COLLECTIONS_START: 'SET_COLLECTIONS_START',
  SET_COLLECTIONS_SUCCESS: 'SET_COLLECTIONS_SUCCESS',
  SET_COLLECTIONS_FAIL: 'SET_COLLECTIONS_FAIL',
}