export default {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
  EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
  EMAIL_SIGN_IN_SUCCESS: 'EMAIL_SIGN_IN_SUCCESS',
  EMAIL_SIGN_IN_FAIL: 'EMAIL_SIGN_IN_FAIL',
  GOOGLE_SIGN_IN_FAIL: 'EMAIL_SIGN_IN_FAIL',
  GOOGLE_SIGN_IN_SUCCESS: 'EMAIL_SIGN_IN_SUCCESS'
}